version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.10-rc-management-alpine
    ports:
      # AMQP protocol port
      - "5672:5672"
      # HTTP management UI
      - "15672:15672"
    networks:
      - poc-sms-network

  frontend:
    build: ./frontend
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - producer
    networks:
      - poc-sms-network

  producer:
    build:
      context: ./producer
      args:
        - NODE_ENV=development
    ports:
      - "3001:3001"
    volumes:
      - ./producer:/usr/src/app
    environment:
      - SERVICE=producer
    env_file:
      - ./producer/.env
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=60 -- node index.js'
    depends_on:
      - rabbitmq
    networks:
      - poc-sms-network

  consumer:
    build:
      context: ./consumer
      args:
        - NODE_ENV=development
    ports:
      - "3002:3002"
    volumes:
      - ./consumer:/usr/src/app
    environment:
      - SERVICE=consumer
    env_file:
      - ./consumer/.env
    command: sh -c '/bin/wait-for-it.sh rabbitmq:5672 --timeout=60 -- node index.js'
    depends_on:
      - rabbitmq
    networks:
      - poc-sms-network

networks:
  poc-sms-network:
    driver: bridge

    



